// ============================================================
// Core Types
// ============================================================

export interface Player {
  id: string; // UUID generated on connection
  name: string; // 1-20 alphanumeric chars + spaces
  isHost: boolean; // First player to create the room
  isConnected: boolean;
  joinOrder: number; // Used for tiebreaking in leaderboard
}

export interface Room {
  code: string; // 4 uppercase alphanumeric chars
  players: Player[];
  settings: GameSettings;
  game: GameState | null; // null when in lobby
}

export interface GameSettings {
  minPlayers: number; // 3–10, default 4
  maxPlayers: number; // 3–10, default 7
  answerTimerSeconds: number; // 10–300, default 60
  votingTimerSeconds: number; // 10–300, default 30
}

export interface GameState {
  phase: GamePhase;
  currentRound: number; // 1-indexed
  totalRounds: number; // Equal to player count at game start
  questions: number[]; // Indices into question bank (pre-selected)
  featuredPlayerOrder: string[]; // Player IDs in featured order
  scores: Record<string, number>; // playerId → cumulative score
  currentRoundState: RoundState;
}

export type GamePhase =
  | "lobby"
  | "question_display"
  | "answer_phase"
  | "voting_phase"
  | "score_reveal"
  | "game_end";

export interface RoundState {
  questionIndex: number;
  featuredPlayerId: string;
  questionText: string; // With XYZ replaced
  answers: Record<string, string>; // playerId → answer text
  votes: Record<string, string>; // voterId → answerId (playerId of answer author)
  timerEndTime: number; // Unix timestamp when current timer expires
}

export interface LeaderboardEntry {
  playerId: string;
  playerName: string;
  score: number;
  rank: number;
}

export interface RoundResult {
  playerId: string;
  playerName: string;
  answer: string;
  voteCount: number;
  pointsEarned: number;
}

// ============================================================
// WebSocket Message Protocol
// ============================================================

// --- Connection & Room Messages ---

/** Client → Server (first message, not relayed) */
export interface JoinRoomMessage {
  type: "join_room";
  roomCode: string;
  playerId: string;
}

/** Client → Room (relayed to all others) */
export interface PlayerJoinedMessage {
  type: "player_joined";
  player: Player;
}

/** Server → Room (generated by server on disconnect) */
export interface PlayerDisconnectedMessage {
  type: "player_disconnected";
  playerId: string;
}

/** Client → Room (on reconnection) */
export interface PlayerReconnectedMessage {
  type: "player_reconnected";
  player: Player;
}

// --- Game Flow Messages ---

/** Host → Room */
export interface GameStartMessage {
  type: "game_start";
  settings: GameSettings;
  questions: number[]; // Pre-selected question indices
  featuredPlayerOrder: string[]; // Randomized player order
  totalRounds: number;
}

/** Host → Room (at start of each round) */
export interface RoundBeginMessage {
  type: "round_begin";
  roundNumber: number;
  questionIndex: number;
  featuredPlayerId: string;
  questionText: string;
}

/** Player → Room */
export interface AnswerSubmitMessage {
  type: "answer_submit";
  playerId: string;
  answer: string;
  roundNumber: number;
}

/** Any client → Room (when all answers in or timer expires) */
export interface VotingPhaseStartMessage {
  type: "voting_phase_start";
  answers: Array<{ answerId: string; text: string }>; // Randomized, no author info
}

/** Player → Room */
export interface VoteCastMessage {
  type: "vote_cast";
  voterId: string;
  answerId: string;
  roundNumber: number;
}

/** Any client → Room (when all votes in or timer expires) */
export interface ResultsRevealMessage {
  type: "results_reveal";
  results: RoundResult[];
  leaderboard: LeaderboardEntry[];
}

// --- Consensus Messages ---

/** Client → Room (at each phase boundary) */
export interface StateHashMessage {
  type: "state_hash";
  playerId: string;
  hash: string;
  phase: GamePhase;
  roundNumber: number;
}

/** Client → specific client (via room broadcast, filtered by recipient) */
export interface StateRequestMessage {
  type: "state_request";
  requesterId: string;
  targetId: string;
}

/** Client → Room (in response to state_request) */
export interface FullStateMessage {
  type: "full_state";
  senderId: string;
  targetId: string;
  state: GameState;
}

// --- Settings Messages ---

/** Host → Room */
export interface SettingsUpdateMessage {
  type: "settings_update";
  settings: GameSettings;
}

/** Host → Room (sent when a new player joins to sync the full player list) */
export interface RoomSyncMessage {
  type: "room_sync";
  players: Player[];
  settings: GameSettings;
}

// ============================================================
// Union type of all WebSocket messages
// ============================================================

export type WebSocketMessage =
  | JoinRoomMessage
  | PlayerJoinedMessage
  | PlayerDisconnectedMessage
  | PlayerReconnectedMessage
  | GameStartMessage
  | RoundBeginMessage
  | AnswerSubmitMessage
  | VotingPhaseStartMessage
  | VoteCastMessage
  | ResultsRevealMessage
  | StateHashMessage
  | StateRequestMessage
  | FullStateMessage
  | SettingsUpdateMessage
  | RoomSyncMessage;

// ============================================================
// GameAction union type for the reducer
// ============================================================

export type GameAction =
  | { type: "ADD_PLAYER"; player: Player }
  | { type: "REMOVE_PLAYER"; playerId: string }
  | { type: "SYNC_PLAYERS"; players: Player[]; settings: GameSettings }
  | {
      type: "START_GAME";
      settings: GameSettings;
      questions: number[];
      featuredOrder: string[];
    }
  | {
      type: "BEGIN_ROUND";
      roundNumber: number;
      questionIndex: number;
      featuredPlayerId: string;
      questionText: string;
    }
  | { type: "SUBMIT_ANSWER"; playerId: string; answer: string }
  | { type: "CAST_VOTE"; voterId: string; answerId: string }
  | { type: "REVEAL_RESULTS" }
  | { type: "END_GAME" }
  | { type: "APPLY_FULL_STATE"; state: GameState }
  | { type: "UPDATE_SETTINGS"; settings: GameSettings };
